import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "categories_locales" (
  	"title" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );
  
  DROP INDEX "posts_rels_pages_id_idx";
  DROP INDEX "posts_rels_posts_id_idx";
  DROP INDEX "posts_rels_categories_id_idx";
  DROP INDEX "posts_rels_users_id_idx";
  DROP INDEX "_posts_v_rels_pages_id_idx";
  DROP INDEX "_posts_v_rels_posts_id_idx";
  DROP INDEX "_posts_v_rels_categories_id_idx";
  DROP INDEX "_posts_v_rels_users_id_idx";
  ALTER TABLE "posts_blocks_camp_facts_facts" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_facts" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_gallery_images" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_gallery_icons" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_gallery" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_hero_links" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_hero" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_main" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_sponsors_sponsors" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_camp_sponsors" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_content_columns" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_content" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_html_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_iframe_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_media_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_form_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_blocks_gallery_timeline" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "posts_populated_authors" ADD COLUMN "role" varchar;
  ALTER TABLE "posts_locales" ADD COLUMN "title" varchar;
  ALTER TABLE "posts_locales" ADD COLUMN "content" jsonb;
  ALTER TABLE "posts_rels" ADD COLUMN "locale" "_locales";
  ALTER TABLE "_posts_v_blocks_camp_facts_facts" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_facts" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_gallery_images" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_gallery_icons" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_gallery" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_hero_links" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_hero" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_main" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_sponsors_sponsors" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_camp_sponsors" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_content_columns" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_content" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_html_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_iframe_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_media_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_form_block" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_blocks_gallery_timeline" ADD COLUMN "_locale" "_locales" NOT NULL;
  ALTER TABLE "_posts_v_version_populated_authors" ADD COLUMN "role" varchar;
  ALTER TABLE "_posts_v_locales" ADD COLUMN "version_title" varchar;
  ALTER TABLE "_posts_v_locales" ADD COLUMN "version_content" jsonb;
  ALTER TABLE "_posts_v_rels" ADD COLUMN "locale" "_locales";
  ALTER TABLE "users" ADD COLUMN "role" varchar;
  ALTER TABLE "categories_locales" ADD CONSTRAINT "categories_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "categories_locales_locale_parent_id_unique" ON "categories_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "posts_blocks_camp_facts_facts_locale_idx" ON "posts_blocks_camp_facts_facts" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_facts_locale_idx" ON "posts_blocks_camp_facts" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_gallery_images_locale_idx" ON "posts_blocks_camp_gallery_images" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_gallery_icons_locale_idx" ON "posts_blocks_camp_gallery_icons" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_gallery_locale_idx" ON "posts_blocks_camp_gallery" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_hero_links_locale_idx" ON "posts_blocks_camp_hero_links" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_hero_locale_idx" ON "posts_blocks_camp_hero" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_main_locale_idx" ON "posts_blocks_camp_main" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_sponsors_sponsors_locale_idx" ON "posts_blocks_camp_sponsors_sponsors" USING btree ("_locale");
  CREATE INDEX "posts_blocks_camp_sponsors_locale_idx" ON "posts_blocks_camp_sponsors" USING btree ("_locale");
  CREATE INDEX "posts_blocks_content_columns_locale_idx" ON "posts_blocks_content_columns" USING btree ("_locale");
  CREATE INDEX "posts_blocks_content_locale_idx" ON "posts_blocks_content" USING btree ("_locale");
  CREATE INDEX "posts_blocks_html_block_locale_idx" ON "posts_blocks_html_block" USING btree ("_locale");
  CREATE INDEX "posts_blocks_iframe_block_locale_idx" ON "posts_blocks_iframe_block" USING btree ("_locale");
  CREATE INDEX "posts_blocks_media_block_locale_idx" ON "posts_blocks_media_block" USING btree ("_locale");
  CREATE INDEX "posts_blocks_form_block_locale_idx" ON "posts_blocks_form_block" USING btree ("_locale");
  CREATE INDEX "posts_blocks_gallery_timeline_locale_idx" ON "posts_blocks_gallery_timeline" USING btree ("_locale");
  CREATE INDEX "posts_rels_locale_idx" ON "posts_rels" USING btree ("locale");
  CREATE INDEX "_posts_v_blocks_camp_facts_facts_locale_idx" ON "_posts_v_blocks_camp_facts_facts" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_facts_locale_idx" ON "_posts_v_blocks_camp_facts" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_gallery_images_locale_idx" ON "_posts_v_blocks_camp_gallery_images" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_gallery_icons_locale_idx" ON "_posts_v_blocks_camp_gallery_icons" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_gallery_locale_idx" ON "_posts_v_blocks_camp_gallery" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_hero_links_locale_idx" ON "_posts_v_blocks_camp_hero_links" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_hero_locale_idx" ON "_posts_v_blocks_camp_hero" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_main_locale_idx" ON "_posts_v_blocks_camp_main" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_sponsors_sponsors_locale_idx" ON "_posts_v_blocks_camp_sponsors_sponsors" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_camp_sponsors_locale_idx" ON "_posts_v_blocks_camp_sponsors" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_content_columns_locale_idx" ON "_posts_v_blocks_content_columns" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_content_locale_idx" ON "_posts_v_blocks_content" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_html_block_locale_idx" ON "_posts_v_blocks_html_block" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_iframe_block_locale_idx" ON "_posts_v_blocks_iframe_block" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_media_block_locale_idx" ON "_posts_v_blocks_media_block" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_form_block_locale_idx" ON "_posts_v_blocks_form_block" USING btree ("_locale");
  CREATE INDEX "_posts_v_blocks_gallery_timeline_locale_idx" ON "_posts_v_blocks_gallery_timeline" USING btree ("_locale");
  CREATE INDEX "_posts_v_rels_locale_idx" ON "_posts_v_rels" USING btree ("locale");
  CREATE INDEX "posts_rels_pages_id_idx" ON "posts_rels" USING btree ("pages_id","locale");
  CREATE INDEX "posts_rels_posts_id_idx" ON "posts_rels" USING btree ("posts_id","locale");
  CREATE INDEX "posts_rels_categories_id_idx" ON "posts_rels" USING btree ("categories_id","locale");
  CREATE INDEX "posts_rels_users_id_idx" ON "posts_rels" USING btree ("users_id","locale");
  CREATE INDEX "_posts_v_rels_pages_id_idx" ON "_posts_v_rels" USING btree ("pages_id","locale");
  CREATE INDEX "_posts_v_rels_posts_id_idx" ON "_posts_v_rels" USING btree ("posts_id","locale");
  CREATE INDEX "_posts_v_rels_categories_id_idx" ON "_posts_v_rels" USING btree ("categories_id","locale");
  CREATE INDEX "_posts_v_rels_users_id_idx" ON "_posts_v_rels" USING btree ("users_id","locale");
  ALTER TABLE "posts" DROP COLUMN "title";
  ALTER TABLE "posts" DROP COLUMN "content";
  ALTER TABLE "_posts_v" DROP COLUMN "version_title";
  ALTER TABLE "_posts_v" DROP COLUMN "version_content";
  ALTER TABLE "categories" DROP COLUMN "title";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "categories_locales" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "categories_locales" CASCADE;
  DROP INDEX "posts_blocks_camp_facts_facts_locale_idx";
  DROP INDEX "posts_blocks_camp_facts_locale_idx";
  DROP INDEX "posts_blocks_camp_gallery_images_locale_idx";
  DROP INDEX "posts_blocks_camp_gallery_icons_locale_idx";
  DROP INDEX "posts_blocks_camp_gallery_locale_idx";
  DROP INDEX "posts_blocks_camp_hero_links_locale_idx";
  DROP INDEX "posts_blocks_camp_hero_locale_idx";
  DROP INDEX "posts_blocks_camp_main_locale_idx";
  DROP INDEX "posts_blocks_camp_sponsors_sponsors_locale_idx";
  DROP INDEX "posts_blocks_camp_sponsors_locale_idx";
  DROP INDEX "posts_blocks_content_columns_locale_idx";
  DROP INDEX "posts_blocks_content_locale_idx";
  DROP INDEX "posts_blocks_html_block_locale_idx";
  DROP INDEX "posts_blocks_iframe_block_locale_idx";
  DROP INDEX "posts_blocks_media_block_locale_idx";
  DROP INDEX "posts_blocks_form_block_locale_idx";
  DROP INDEX "posts_blocks_gallery_timeline_locale_idx";
  DROP INDEX "posts_rels_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_facts_facts_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_facts_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_gallery_images_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_gallery_icons_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_gallery_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_hero_links_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_hero_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_main_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_sponsors_sponsors_locale_idx";
  DROP INDEX "_posts_v_blocks_camp_sponsors_locale_idx";
  DROP INDEX "_posts_v_blocks_content_columns_locale_idx";
  DROP INDEX "_posts_v_blocks_content_locale_idx";
  DROP INDEX "_posts_v_blocks_html_block_locale_idx";
  DROP INDEX "_posts_v_blocks_iframe_block_locale_idx";
  DROP INDEX "_posts_v_blocks_media_block_locale_idx";
  DROP INDEX "_posts_v_blocks_form_block_locale_idx";
  DROP INDEX "_posts_v_blocks_gallery_timeline_locale_idx";
  DROP INDEX "_posts_v_rels_locale_idx";
  DROP INDEX "posts_rels_pages_id_idx";
  DROP INDEX "posts_rels_posts_id_idx";
  DROP INDEX "posts_rels_categories_id_idx";
  DROP INDEX "posts_rels_users_id_idx";
  DROP INDEX "_posts_v_rels_pages_id_idx";
  DROP INDEX "_posts_v_rels_posts_id_idx";
  DROP INDEX "_posts_v_rels_categories_id_idx";
  DROP INDEX "_posts_v_rels_users_id_idx";
  ALTER TABLE "posts" ADD COLUMN "title" varchar;
  ALTER TABLE "posts" ADD COLUMN "content" jsonb;
  ALTER TABLE "_posts_v" ADD COLUMN "version_title" varchar;
  ALTER TABLE "_posts_v" ADD COLUMN "version_content" jsonb;
  ALTER TABLE "categories" ADD COLUMN "title" varchar NOT NULL;
  CREATE INDEX "posts_rels_pages_id_idx" ON "posts_rels" USING btree ("pages_id");
  CREATE INDEX "posts_rels_posts_id_idx" ON "posts_rels" USING btree ("posts_id");
  CREATE INDEX "posts_rels_categories_id_idx" ON "posts_rels" USING btree ("categories_id");
  CREATE INDEX "posts_rels_users_id_idx" ON "posts_rels" USING btree ("users_id");
  CREATE INDEX "_posts_v_rels_pages_id_idx" ON "_posts_v_rels" USING btree ("pages_id");
  CREATE INDEX "_posts_v_rels_posts_id_idx" ON "_posts_v_rels" USING btree ("posts_id");
  CREATE INDEX "_posts_v_rels_categories_id_idx" ON "_posts_v_rels" USING btree ("categories_id");
  CREATE INDEX "_posts_v_rels_users_id_idx" ON "_posts_v_rels" USING btree ("users_id");
  ALTER TABLE "posts_blocks_camp_facts_facts" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_facts" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_gallery_images" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_gallery_icons" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_gallery" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_hero_links" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_hero" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_main" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_sponsors_sponsors" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_camp_sponsors" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_content_columns" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_content" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_html_block" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_iframe_block" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_media_block" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_form_block" DROP COLUMN "_locale";
  ALTER TABLE "posts_blocks_gallery_timeline" DROP COLUMN "_locale";
  ALTER TABLE "posts_populated_authors" DROP COLUMN "role";
  ALTER TABLE "posts_locales" DROP COLUMN "title";
  ALTER TABLE "posts_locales" DROP COLUMN "content";
  ALTER TABLE "posts_rels" DROP COLUMN "locale";
  ALTER TABLE "_posts_v_blocks_camp_facts_facts" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_facts" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_gallery_images" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_gallery_icons" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_gallery" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_hero_links" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_hero" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_main" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_sponsors_sponsors" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_camp_sponsors" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_content_columns" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_content" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_html_block" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_iframe_block" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_media_block" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_form_block" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_blocks_gallery_timeline" DROP COLUMN "_locale";
  ALTER TABLE "_posts_v_version_populated_authors" DROP COLUMN "role";
  ALTER TABLE "_posts_v_locales" DROP COLUMN "version_title";
  ALTER TABLE "_posts_v_locales" DROP COLUMN "version_content";
  ALTER TABLE "_posts_v_rels" DROP COLUMN "locale";
  ALTER TABLE "users" DROP COLUMN "role";`)
}
